apiVersion: v1
kind: Secret
metadata:
  name: gdm-articles-api-secrets
  labels:
    app: gdm-articles-api
data:
  DATABASE_PASSWORD: {{ .Values.database.user_password | b64enc }}
  DATABASE_SU_PASSWORD: {{ .Values.database.su_password | b64enc }}
