database:
    user_password: ENC[AES256_GCM,data:s4tzKYIKxhL0XdzB9q6Nbis8O6Lep1A3NgEK0BE0xvo=,iv:Z9pMHlSRq7B3hAImL+oUiZWAEtbWKaDP06DxvyfmRX0=,tag:+9sDaDbL3/5kq4qQNh0hoA==,type:str]
    su_password: ENC[AES256_GCM,data:k4K8HVbM51iVw7t4YYIYYA4ImD6lR6iul1eqad4SDxU=,iv:++ifjoxctB2eFeO6nyxIyyUWiDTb6OZi0N91oxDoaKw=,tag:z5FZtneW5z0N1Q2+cuws1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://sh-us-dev-keyvault.vault.azure.net
        name: gdm-articles-api-sops
        version: 12c54a76d25a4e99b49d13114ad55e92
        created_at: '2021-01-08T16:41:16Z'
        enc: lyPgV8nM_lNv2pQNT6l9pkPb2BLVs51qDl_kMlfZkq-YiNqHwe8phbC1H7V1RWpfUldK7xQ9WtTAnW9o7l4ealqwXm49PsrxFmg5QC4EANVeoIOKCuPmHdqcOLe-ENaUPG3M59N1Ic519aUpbg9nlxrmhkQSz7kg4Q4GFKtDRTUEDmjVTa2rEr3uA36lprSFNwKJHa_T-QqsYy2rQWxRGId2flc-A2lCLKKnvzaz-l3jC-bYZr3vZIXi-K00qIJTXtQdtEsBkdgWltE7ACg-2hfNvs7bOAkf7wjSg3Sfx1xWh4hh2bXFjazsWjs1qT59rY0KUMWJJBOMPs98QmQAYQ
    hc_vault: []
    lastmodified: '2021-01-08T16:42:38Z'
    mac: ENC[AES256_GCM,data:zNc/7WUoSZsj1pLCxe7kny2Dsv9L8e0YbR0nBUYNsE7J9aTB396u4GnqrwQWyAkY2WgZYoU4oWccmOlTPBzoBQ7IGgC5W/JpJrN3Fe3vubdPPLM6+VDgNzWWj9xZwSt/8t0rCZqszSfQgB+I+93SJ/vmeNOd5RdgSlwSz3HsPNM=,iv:ByE5bwUOdtTSp8teID8CTVvm3P4hqoywUY+SaHdaqo4=,tag:ulSRxG1jxEEYaU0jEGZt7Q==,type:str]
    pgp:
    -   created_at: '2021-01-08T16:41:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA6zMWHGWY4fTAQf8DfGO+koCBEWr2CQykGkNyvS9xROSB/TI7lGAuEV5SQn1
            ZSJuJ1gfcQYbK7j6FDNXRCTWxObUuejgD3ADu20vPQt3R5TnaWnirt7Mcfm5AAhD
            Baj2e9OeXa6u4D/2/BlfxdVzB2kvjHI36yV8bEon6JuqyvjcqLrz9Mvqpkx+6TQN
            AKA/lPJBHNhusx3CkjpP8oUOmpNOvQ+IpoOfbVTWevK+c4hjKBt27MKFNaZ8QlYW
            nsrj1Jxg44gr1kdWp7GGhl9rySFuuPkXaNhHFIhB8JGwapqu5PfA670hngqeHnXX
            DU5KqN3gNWfc2+Sp0fuQCx/jX4FTw1GFmwj8aLFL69JeAVw834uPIge1DwA7FU00
            hwjQ8yMqhY83aWCkciUkxjxVSB7zwR6SS+mtVf1olbo2yrTwLIEKPzAPxCJR2Jbm
            cb7Yi/dnPpWDYRSG8tkeLr3zpfcxpPq+uWvPUP5WmQ==
            =3n6M
            -----END PGP MESSAGE-----
        fp: 8872B8F99E83960708A51F9BA6B64CBF0636EFDA
    unencrypted_suffix: _unencrypted
    version: 3.6.1
