database:
  host: uk-nonprod-upstream-api001-shepherd-db.postgres.database.azure.com
  user_name: gdm-articles@uk-nonprod-upstream-api001-shepherd-db
  su_name: postgres@uk-nonprod-upstream-api001-shepherd-db
  name: gdm-articles

imagePullPolicy: Always
# This placeholder value gets overridden by devops-release-config during a release
imagetag: r1.11.0

host_env: azure

# proxy_url is the tyk api gateway URL
gdm_articles_www: https://api-uk-nonprod.sensynehealth.com/gdm-articles
proxy_url: https://api-uk-nonprod.sensynehealth.com

environment: NONPRODUCTION

allow_drop_data: false

ingress:
  hostName: api-nonprod.sensynehealth.local
