database:
  host: uk-prod006-hog-db.postgres.database.azure.com
  user_name: gdm-articles@uk-prod006-hog-db
  su_name: postgres@uk-prod006-hog-db
  name: gdm-articles

imagePullPolicy: IfNotPresent
# This placeholder value gets overridden by devops-release-config-prod during a release
imagetag: r1.8.0

host_env: azure

# proxy_url is the tyk api gateway URL
gdm_articles_www: https://api-uk-prod.sensynehealth.com/gdm-articles
proxy_url: https://api-uk-prod.sensynehealth.com

environment: PRODUCTION

allow_drop_data: false

ingress:
  hostName: api-prod.sensynehealth.local
