database:
  host: us-prod-upstream-api001-oriole-db.postgres.database.azure.com
  user_name: gdm-articles@us-prod-upstream-api001-oriole-db
  su_name: postgres@us-prod-upstream-api001-oriole-db
  name: gdm-articles

imagePullPolicy: IfNotPresent
# This placeholder value gets overridden by devops-release-config-prod during a release
imagetag: r1.12.0

host_env: azure

# proxy_url is the tyk api gateway URL
gdm_articles_www: https://api-us-prod.sensynehealth.com/gdm-articles
proxy_url: https://api-us-prod.sensynehealth.com

environment: PRODUCTION

allow_drop_data: false

ingress:
  hostName: api-prod.sensynehealth.local
