database:
    user_password: ENC[AES256_GCM,data:T73K7/iXiLz6zAh5zALOIoF5OO89h85Qh84NT+J5eow=,iv:98koL4VJpStvpwlwpQ7DkSLfpoV9bXTFC+FPLyW0OZY=,tag:bhe+5JNvHFc61LGRCFW48g==,type:str]
    su_password: ENC[AES256_GCM,data:mRFCFZf9q5fT5Bk5nakW9azUlMKbyLZzy0Gv2EoD0dk=,iv:Lp8QpXcFRbsBiZvp3Zf/vfYmzts8nenOK0SL75lXxKs=,tag:g9v2wV0gPhmKuA+uY2Ld3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://uk-prod-keyvault.vault.azure.net
        name: gdm-articles-api-sops
        version: c3bb11b83aa64cc3909ea745b1acdab9
        created_at: '2020-09-28T15:56:33Z'
        enc: UTUKGpsWI7m7u6GTXrXYRSAbnErUnONQ9R9Ky3UORcV0YwECUnLkPjuUYC7vfJNph_Y8apdNy89Ua8SzZgKi-vgLgWMHowm210HDfzQ5FChmI0uL0Zhu5Nq5wru8DtV2cVQ77v_Y4gw_RzRNMs6VtGPKkZ8tKxDT1VGSG3L49AE9W7eX2--1zGwtpOGLHi2Nt-tplUfp0ZuIAi3G9BBPiLGqCSS9jEsg6M7IgpvUIwmLMSTIMMLwzohw3JFlkHx_nH-RvvMobFkRJcGQEidfgi7KpP6FyBmL49ADUR5Y8AKAPW95SmW3CKGbU3L0JDivw9DWlfvhOJG8EYf3d28KSA
    hc_vault: []
    lastmodified: '2020-11-03T14:50:23Z'
    mac: ENC[AES256_GCM,data:m7WLfSaQpuyjqDghVQLPeGyG9HQYgt/0DyhP2aQA+5Vn8JjeDmZPtXe5ZuisxWuU2Fzc5NYivQciCoy0t0nUn7gCeLHFtsqRRNdFYtUDAgUG7nN5cdt3y3dL62WEURxOTbGl3JlZPF4SVSkP3+4guhFRpqSUO/trDDWTG+y1PVM=,iv:tn1LqwTWMjtQcKkFJ3hI1g8H666dQ5ojei+5XU5QGX4=,tag:i5dAahuRu938fDuRxPxBpQ==,type:str]
    pgp:
    -   created_at: '2020-09-28T15:56:34Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA6zMWHGWY4fTAQgAlfuUnzKPhI5aZnm/+YZnytH8hDOe6+m+O3HSbifEd7mh
            dQJQhr8UXeDUfaY+SPNo0BY03+8onP451rsFl+r76eiT90/OX8rSCGSNzJO6NRwh
            mEpcG8KKSdkzIgG8J6Y9jJrGE0paQ1y+g0Qu7ficLvoYo5/sEiUgrrZ8oulNKmRK
            P1aNOSLS/E1UyxRPqORLWDiwAQd0VPwBmbQO1Z8ugVqYLHfMb/YTUTnXyz8R01wL
            llFX4BaVX/h7nkJ6nNa/IUBrPSm7xsWGnIONRX+BOx7QV3Jo5grjYINV5vzkaCco
            wBBPrKV3K5y6BIOycio5S5Tv9AiQAq2f/KYfOX+WU9JeAWzXvPsws3kORy5/6Ihi
            +Di/8gVmEXiJqPH5MrCIh94/wDi6/NXPv/atyMK7kyw9TeLhgbql1hcKQwx8tYla
            NGtIFeG2KjRRbOlRwyR9JprUeUhUHYxAhnt7NbR5kA==
            =kCbc
            -----END PGP MESSAGE-----
        fp: 8872B8F99E83960708A51F9BA6B64CBF0636EFDA
    unencrypted_suffix: _unencrypted
    version: 3.6.1
