database:
    user_password: ENC[AES256_GCM,data:ZDGVZB9JA79dpBrdYkicevp2fppn7hhygD3vdYhIKOM=,iv:sNiIlXbxl2Gf7lYfog9jLWjkwUCFe9CiTvDBt4cL7k0=,tag:D2mYmHytDjiycopnezCIrA==,type:str]
    su_password: ENC[AES256_GCM,data:puKJl9A3aOf/+BdgH7KQWVUoeXMRYf9OJJHaJgBnJvY=,iv:SXlcCgVARvvMYJJZvvzYM38JKY01gaoWdk459fKC1MI=,tag:NAs8C2LC1LkuDk1xRhNjVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://us-nonprod-keyvault.vault.azure.net
        name: gdm-articles-api-sops
        version: 67538a4e6e6f48f394f447d848b48155
        created_at: '2021-01-25T08:36:44Z'
        enc: V2Hy_rfClMD2msSAOREht7be4h2pyxlz-Q3krtYY9y0QRk36naZjvHncipsKDJ3CqQEWgK3JZAQJD2PEOS17AumfM_69jwrJ46nyDbXECpqe2NZd05IuNMvwKemUEnb59aFvAfzVz49kfaSgVjWmOvjOmaDqPx76pCkpNdsMAEm9ZiEBP-3-h01nKvQ4NF3hsDXlt15XeQ9pEHhZi6NfmESwQbAzApbbcDB2PivQ15YUytJV56b0W2Ukimc_xCPnRQpbYbFeSON_k-pd-w4fS9_q3tJomZxQU8LTxenfNy_ga5dkU08p9EQsmGj0e96P67hFymmrcM4SKwT33GlVrQ
    hc_vault: []
    lastmodified: '2021-01-25T08:36:49Z'
    mac: ENC[AES256_GCM,data:GGicClrjsWtVdCmuZnBuJS49p6GUiGie3JVWj0WrIVzQzK51olw/j1pSoQgSZGO550tzVa4P8+j22wUai4r5bx+OoNhrW1uEaWlavX0yMYKZgosnq5hyhIAkOMjJLMF9V/LHmY8ihFv1Z8sHzqrEoDjkEC20Y69qAAEePgy4jm0=,iv:msBRyIlGk2e3NjLsW2u//UN4EBDAPfAU5UlgJ4Fc8zQ=,tag:5s9RJYbblDJ0LQSmR+2p8g==,type:str]
    pgp:
    -   created_at: '2021-01-25T08:36:45Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA6zMWHGWY4fTAQf/V35PZl01rSI/ic19+//tvK4hRJg+LQBU2FRWaWIKZITQ
            uqypbqLxU44TGwjWinQuSTOoIXjJPr8BrS380r5NVVX24kuwQkdUfA1a2ZmvcAD4
            l9cyRDPrmEk7I0pfHfy521BrHaz/vKyYhgIZE1TdFeRLZX1SMyuyuuaM1pwGwbOz
            lRP7ZoYiofOWA4/F5pler/G/Gp5WuPqp56yct3UCLONpQolQbNvde7FhBXrSq7vg
            p3G9sausI8qFHZhg6Rp//B9CFchuPhGNyT/i21ojCSSqzTSADoVZZCsVQVFkSp6s
            bVrf/fzfMb6DAAMsYhF8VAcB0uSPOenDxeJIVmKeftJeAfhKVnuTFycsGJzn3Rna
            eGDGm5s0xHcf0QoUhyrmwkSJYOia4J4OO9G0SoLmLvHX+WWT1ExeR4BllmKyuErf
            nigpAtdtPkk/ogEdnHYixIlq0zc9ADjg3c410tgiCg==
            =qUkG
            -----END PGP MESSAGE-----
        fp: 8872B8F99E83960708A51F9BA6B64CBF0636EFDA
    unencrypted_suffix: _unencrypted
    version: 3.6.1
